# LogViewer Configuration File
# This file contains default configuration settings for the LogViewer application

# Display settings
display:
  font_family: "Consolas"
  font_size: 12
  background_color: "#ffffff"
  text_color: "#000000"

# Highlighting configuration
highlighting:
  enabled: true
  terms:
    - pattern: "ERROR"
      color: "#ff0000"
      background: "#ffdddd"
    - pattern: "WARNING"
      color: "#ff8800"
      background: "#fff3dd"
    - pattern: "INFO"
      color: "#0088ff"
      background: "#ddddff"
    - pattern: "DEBUG"
      color: "#888888"
      background: "#f5f5f5"

# Search settings
search:
  case_sensitive: false
  regex_enabled: false
  highlight_all: true

# File handling
file:
  max_file_size_mb: 100
  auto_reload: true
  encoding: "utf-8"

# UI settings
ui:
  window_width: 1200
  window_height: 800
  show_line_numbers: true
  wrap_text: false
